baseURL: "https://binarymusings.org"
title: Binary Musings - CoolCode
copyright: "© 2025 Garry Chen"
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "golang", "javascript", "c++"]

minify:
  disableXML: true
  minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Contact
          url: contact-us/
          weight: 15
        # - name: WiKi
        #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
  section:
    - HTML
    - RSS

sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Binary Musings - Programming tutorials, tech insights, and coding best practices. Learn C++, JavaScript, Go, and modern development techniques."
  keywords: ["programming", "coding", "technology", "tutorials", "C++", "JavaScript", "Go", "software development", "tech blog"]
  author: Garry Chen
  # author: ["Me", "You"] # multiple authors
  images: ["images/binary.png"] # Default social sharing image

  footer:
    text: '[Contact](/contact-us/) · [Privacy Policy](/privacy-policy/) · [Terms & Conditions](/terms-conditions/)'

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  
  # SEO and Social Media
  opengraph: true
  twitter_cards: true

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Binary Musings"
    Content: >
      Welcome! Musings on technology, learning actively, and thinking independently in the age of AI.


  socialIcons:
    # - name: github
    #   title: View Source on Github
    #   url: "https://github.com/GarryChen-site"
    # - name: Discord
    #   title: Join discord community
    #   url: "https://discord.gg/ahpmTvhVmp"
    # - name: X
    #   title: Share PaperMod on X/Twitter
    #   url: "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"
    # - name: KoFi
    #   title: Buy me a Ko-Fi :)
    #   url: "https://ko-fi.com/garrychen"

  editPost:
    URL: "https://github.com/GarryChen-site/binarymusings"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #   google:
  #     SiteVerificationTag: "G-Y5HTF2LVH4"

  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

  privacy:
    vimeo:
      disabled: false
      simple: true
    twitter:
      disabled: false
      enableDNT: true
      simple: true
    instagram:
      disabled: false
      simple: true
    youtube:
      disabled: false
      privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
  googleAnalytics:
    id: G-Y5HTF2LVH4
